name: build-lollms-webui
on:
    push:
        branches:
         main
permissions:
  actions: read           # for detecting the Github Actions environment
  id-token: write         # for creating OIDC tokens for signing
  packages: write         # for uploading attestations
  contents: read          # read the contents permission
  security-events: write  # for uploading code scanning
jobs:
    build-publish-python:
        runs-on: ubuntu-latest              
        env:
          DOCKER_REPO: 'w2-week2-oci-dev-virtual'
          IMAGE_NAME: 'my-python-image-with-security-issues:${{ github.run_number }}'
          JF_URL: https://${{ vars.JF_URL }}/
          DOCKER_CLI_EXPERIMENTAL: enabled
        steps:
            # Use the specific setup-cli branch
            - name: Setup JFrog CLI
              uses: jfrog/setup-jfrog-cli@v4
              id: setup-cli
              env:
                 JF_PROJECT: sai
              with:
                  oidc-provider-name: rodolphef-lollms-webui
                  oidc-audience: rodolphef-lollms-webui-audience

            - name: Checkout the repository
              uses: actions/checkout@v4


            - name: configure jfrog environment
              run: |
                # Use a curated repository for python dependencies resolution
                jf pip-config --repo-resolve=soleng-pypi-dev-virtual   

            - name: build project
              run: |                                   
                jf pip install -r requirements.txt
            - name: Docker build
              run: |
                docker build -t ${{ env.JF_URL }}${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.run_number }} .

            - name: Docker push with JFrog CLI
              run: |
                jf docker-push ${{ env.JF_URL }}${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.run_number }} ${{ env.DOCKER_REPO }} \
                  --build-name=lollms-webui \
                  --build-number=${{ github.run_number }} 
 
            - name: publish build info
              run: |
                jf rt build-collect-env 
                jf rt build-add-dependencies .
                jf rt build-add-git
                jf rt build-publish lollms-webui ${{ github.run_number }}

            - name: build scan
              run: |            
                 jf build-scan lollms-webui ${{ github.run_number }}
                
            - name: Write to workflow job summary
              run: |
                    NOTE=$'>[!NOTE]\n>Frog Notes \n'
                    TIP=$'>[!TIP]\n>Hello JFrog\n'
                    IMPORTANT=$'>[!IMPORTANT]\n>Hello IMPORTANT NOTE\n'
                    WARNING=$'>[!WARNING]\n>Hello WARNING NOTE\n'
                    CAUTION=$'>[!CAUTION]\n>Hello CAUTION NOTE\n'
                    echo "$NOTE" >> $GITHUB_STEP_SUMMARY
                    echo "$TIP" >> $GITHUB_STEP_SUMMARY
                    echo "$IMPORTANT" >> $GITHUB_STEP_SUMMARY
                    echo "$WARNING" >> $GITHUB_STEP_SUMMARY
                    echo "$CAUTION" >> $GITHUB_STEP_SUMMARY